// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zplgoxifsxiokuuktqen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwbGdveGlmc3hpb2t1dWt0cWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzExNzQsImV4cCI6MjA2Mzc0NzE3NH0.do7oyUVe9KTTJxyO9ezxp4vh9kJh_m4_jq-_CDakj74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);